FROM golang:1.13 AS build
WORKDIR /go/src
COPY {{sourceFolder}} ./{{sourceFolder}}
COPY main.go .

ENV CGO_ENABLED=0
RUN go get -d -v ./...

RUN go build -a -installsuffix cgo -o {{packageName}} .

FROM scratch AS runtime
COPY --from=build /go/src/{{packageName}} ./
COPY --from=build /etc/ssl/certs /etc/ssl/certs
EXPOSE 8080/tcp
ENTRYPOINT ["./{{packageName}}"]
